/**
 * Clash Configuration
 * Base configuration template for Clash client
 */

export const CLASH_CONFIG = {
	'port': 7890,
	'socks-port': 7891,
	'allow-lan': true,
	'mode': 'Rule',
	'log-level': 'info',
	'external-controller': ':9090',
	'sniffer': {
		'sniff': {
			'TLS': { 'ports': ['1-65535'], 'override-destination': true },
			'HTTP': { 'ports': ['1-65535'], 'override-destination': true }
		},
		'enable': true,
		'skip-domain': [
			'Mijia Cloud',
			'dlg.io.mi.com'
		],
		'parse-pure-ip': true,
		'force-dns-mapping': true,
		'override-destination': true
	},
	'rule-providers': {
		// 将由代码自动生成
	},
	'dns': {
		'ipv6': false,
		'enable': true,
		'listen': '0.0.0.0:1053',
		'enhanced-mode': 'fake-ip',
		'use-hosts': false,
		'default-nameserver': [
			'119.28.28.28',
			'119.29.29.29',
			'223.5.5.5',
			'223.6.6.6'
		],
		'nameserver': [
			'119.29.29.29',
			'223.5.5.5',
			'tls://dot.pub:853',
			'tls://dns.alidns.com:853',
			'https://doh.pub:443/dns-query',
			'https://dns.alidns.com:443/dns-query'
		],
		'fake-ip-range': '198.18.0.1/15',
		'fake-ip-filter': [
			'*.lan',
			'*.localdomain',
			'*.example',
			'*.invalid',
			'*.localhost',
			'*.test',
			'*.local',
			'*.home.arpa',
			'time.*.com',
			'time.*.gov',
			'time.*.edu.cn',
			'time.*.apple.com',
			'time1.*.com',
			'time2.*.com',
			'time3.*.com',
			'time4.*.com',
			'time5.*.com',
			'time6.*.com',
			'time7.*.com',
			'ntp.*.com',
			'ntp1.*.com',
			'ntp2.*.com',
			'ntp3.*.com',
			'ntp4.*.com',
			'ntp5.*.com',
			'ntp6.*.com',
			'ntp7.*.com',
			'*.time.edu.cn',
			'*.ntp.org.cn',
			'+.pool.ntp.org',
			'time1.cloud.tencent.com',
			'stun.*.*',
			'stun.*.*.*',
			'swscan.apple.com',
			'mesu.apple.com',
			'music.163.com',
			'*.music.163.com',
			'*.126.net',
			'musicapi.taihe.com',
			'music.taihe.com',
			'songsearch.kugou.com',
			'trackercdn.kugou.com',
			'*.kuwo.cn',
			'api-jooxtt.sanook.com',
			'api.joox.com',
			'y.qq.com',
			'*.y.qq.com',
			'streamoc.music.tc.qq.com',
			'mobileoc.music.tc.qq.com',
			'isure.stream.qqmusic.qq.com',
			'dl.stream.qqmusic.qq.com',
			'aqqmusic.tc.qq.com',
			'amobile.music.tc.qq.com',
			'localhost.ptlogin2.qq.com',
			'*.msftconnecttest.com',
			'*.msftncsi.com',
			'*.xiami.com',
			'*.music.migu.cn',
			'music.migu.cn',
			'+.wotgame.cn',
			'+.wggames.cn',
			'+.wowsgame.cn',
			'+.wargaming.net',
			'*.*.*.srv.nintendo.net',
			'*.*.stun.playstation.net',
			'xbox.*.*.microsoft.com',
			'*.*.xboxlive.com',
			'*.ipv6.microsoft.com',
			'teredo.*.*.*',
			'teredo.*.*',
			'speedtest.cros.wr.pvp.net',
			'+.jjvip8.com',
			'www.douyu.com',
			'activityapi.huya.com',
			'activityapi.huya.com.w.cdngslb.com',
			'www.bilibili.com',
			'api.bilibili.com',
			'a.w.bilicdn1.com'
		]
	},
	'proxies': [],
	'proxy-groups': []
};
