name: 上游自动同步

on:
  schedule:
    - cron: '0 0 * * *' # 每天早上 8 点自动同步一次
  workflow_dispatch: # 允许你手动点按钮立刻同步

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 同步上游代码
        uses: a2021lv/sync-upstream-repo@master
        with:
          upstream_repo: "https://github.com/7Sageer/sublink-worker.git"
          upstream_branch: "main"
          downstream_branch: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
