name: 上游自动同步

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点自动同步
  workflow_dispatch: # 允许手动触发

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: 7Sageer/sublink-worker
          upstream_branch: main
          target_branch: main
          test_mode: false}}
